# Generated by Django 5.0.2 on 2026-04-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для аватара', null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
