# Generated by Django 5.0.2 on 2026-03-20 22:15

import django.core.validators
import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_course_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Длительность (часов)'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Курс активен'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый'), ('expert', 'Эксперт')], default='beginner', max_length=50, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимум студентов'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default='2026-03-21', verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[schedule.models.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук'), ('professor', 'Профессор')], default='master', max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='От 0 до 50 лет', validators=[schedule.models.validate_experience_years, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Стаж (лет)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата найма'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7 123 456-78-90', max_length=20, null=True, validators=[schedule.models.validate_phone_number], verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (0-5)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарплата (руб)'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='awards',
            field=models.TextField(blank=True, help_text='Перечислите награды через запятую', verbose_name='Награды и достижения'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='languages',
            field=models.CharField(blank=True, help_text='Например: Английский (C1), Французский (B2)', max_length=200, verbose_name='Иностранные языки'),
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='projects_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество проектов'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Уникальное название курса', max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, validators=[schedule.models.validate_russian_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, validators=[schedule.models.validate_russian_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text='example@school.ru', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text='Только русские буквы', max_length=50, validators=[schedule.models.validate_russian_name], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(help_text='Только русские буквы', max_length=50, validators=[schedule.models.validate_russian_name], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(help_text='Например: Программирование, Математика', max_length=200, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='education',
            field=models.CharField(max_length=300, verbose_name='Образование'),
        ),
    ]
